"""updated model file

Revision ID: e01d2d5dc8e3
Revises: 9c856ad4dc0f
Create Date: 2024-10-06 01:51:34.804085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01d2d5dc8e3'
down_revision = '9c856ad4dc0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_recipe_id_recipes', type_='foreignkey')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_recipe_id_recipes', 'recipes', ['recipe_id'], ['id'])

    # ### end Alembic commands ###
